version: '3'
services:
  web:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - ./projeto:/var/www/html
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webservices
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: